---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: frontend-application-pipeline
spec:
  pipelineRef:
    name: clone-build-push-kaniko
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  - name: docker-credentials
    secret:
      secretName: "${VAULT_KV}-${VAULT_KV_PATH}"
  params:
  - name: repo-url
    value: "${GH_DEV_URL}"

  - name: imageUrl
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/frontend-application"

  - name: pathToDockerfile
    value: "./frontend-application/Dockerfile"

  - name: pathToContext
    value: "frontend-application"

  - name: botTokenSecret
    value: "${VAULT_KV}-${VAULT_KV_PATH}"

  - name: chatIdTelegram
    value: "${TELEGRAM_CHAT_ID}"