---
apiVersion: v1
kind: Secret
metadata:
  name: aws-route53-secret
  namespace: cert-manager
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_BASE_64}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_BASE_64}"

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: thanh.duong@ap.iij.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
      - dns01:
          route53:
            region: "${AWS_DEFAULT_REGION}"
            hostedZoneID: "${AWS_53_HOSTED_ZONE_ID}"
            accessKeyIDSecretRef:
              name: aws-route53-secret
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: aws-route53-secret
              key: AWS_SECRET_ACCESS_KEY
