---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: "promote-${K8S_BE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
spec:
  vars:
  - name: chartURL
    value: "${GH_CHART_URL}"

  - name: chartFolder
    value: ./chart-repo

  - name: sourceImage
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/${K8S_BE_NAME}"

  - name: sourceBranch
    value: main

  - name: privateRepoBE
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/${K8S_BE_NAME}"

  - name: CHART_VALUES_PATH
    value: >-
      ${{
        // Compare ctx.stage with a dynamically constructed string
        ctx.stage == "dev-cluster-01-${K8S_BE_NAME}"       ? "dev"      : 
        ctx.stage == "staging-cluster-01-${K8S_BE_NAME}"   ? "staging"  : 
        ctx.stage == "prod-hcm-cluster-02-${K8S_BE_NAME}"  ? "prod-hcm" : 
        ctx.stage == "prod-hni-cluster-02-${K8S_BE_NAME}"  ? "prod-hni" : 
        "unknown-stage"
      }}

  steps:
  - uses: git-clone
    as: git-clone-chart-repo
    config:
      repoURL: ${{ vars.chartURL }}
      checkout:
      - branch: ${{ vars.sourceBranch }}
        path: ${{ vars.chartFolder }}

  - uses: yaml-update
    as: update-chart-values-file
    config:
      path: ${{ vars.chartFolder }}/${{ vars.CHART_VALUES_PATH }}/values.yml
      updates:
      - key: image.repository
        value: ${{ vars.privateRepoBE }}

      - key: image.tag
        value: ${{ imageFrom("${vars.privateRepoBE}").Tag }}
        
      - key: image.pullPolicy
        value: IfNotPresent

  - uses: git-commit
    as: commit-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      message: "Sync Helm values with thanh-backend-chart"

  - uses: git-push
    as: push-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      targetBranch: main

  - uses: argocd-update
    as: update-chart-repo
    config:
      apps:
      - name: "${{ ctx.stage }}"
        sources:
        - repoURL: "${GH_CHART_URL}"

