---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: "promote-${K8S_BE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
spec:
  vars:
  - name: chartURL
    value: "${GH_CHART_URL}"

  - name: chartFolder
    value: ./chart-repo

  - name: chartRender
    value: ./chart-render

  - name: sourceImage
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/${K8S_BE_NAME}"

  - name: sourceBranch
    value: main

  - name: privateRepoBE
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/${K8S_BE_NAME}"

  - name: CHART_VALUES_PATH
    value: >-
      ${{
        // Compare ctx.stage with a dynamically constructed string
        ctx.stage == "dev-cluster-rs-01-${K8S_BE_NAME}"       ? "thanh-backend-chart/dev"      : 
        ctx.stage == "staging-cluster-rs-01-${K8S_BE_NAME}"   ? "thanh-backend-chart/staging"  : 
        ctx.stage == "prod-hcm-cluster-rs-02-${K8S_BE_NAME}"  ? "thanh-backend-chart/prod-hcm" : 
        ctx.stage == "prod-hni-cluster-rs-02-${K8S_BE_NAME}"  ? "thanh-backend-chart/prod-hni" : 
        "unknown-stage"
      }}

  steps:
  - uses: git-clone
    as: git-clone-chart-repo
    config:
      repoURL: ${{ vars.chartURL }}
      checkout:
      - branch: ${{ vars.sourceBranch }}
        path: ${{ vars.chartFolder }}

  - uses: yaml-update
    as: update-chart-values-file
    config:
      path: ${{ vars.chartFolder }}/${{ vars.CHART_VALUES_PATH }}/values.yml
      updates:
      - key: image.repository
        value: ${{ vars.privateRepoBE }}

      - key: image.tag
        value: ${{ imageFrom(vars.privateRepoBE).Tag }}
        
      - key: image.pullPolicy
        value: IfNotPresent

  - uses: git-commit
    as: commit-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      message: ${{ 'Update Helm values with ' + vars.privateRepoBE + ' version ' + imageFrom(vars.privateRepoBE).Tag }}

  - uses: git-push
    as: push-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      targetBranch: main

  - uses: argocd-update
    as: update-chart-repo
    config:
      apps:
      - name: "${{ ctx.stage }}"
        sources:
        - repoURL: "${GH_CHART_URL}"

  - uses: git-clear
    as: clear-branch-build-artifacts
    config:
      path: ${{ vars.chartRender }}

  - uses: helm-template
    as: helm-render-manifest
    config:
      path: ${{ vars.chartFolder }}/thanh-backend-chart
      releaseName: thanh-backend-chart
      useReleaseName: false
      valuesFiles:
      - ${{ vars.chartFolder }}/${{ vars.CHART_VALUES_PATH }}/values.yml
      outPath: ${{ vars.chartRender }}

  - uses: git-commit
    as: commit-manifest
    config:
      path: ${{ vars.chartRender }}
      message: ${{ 'Update ' + vars.CHART_VALUES_PATH + ' with ' + vars.privateRepoBE + ' to version ' + imageFrom(vars.privateRepoBE).Tag }}
  
  - uses: git-push
    as: push-manifest-branch
    config:
      path: ${{ vars.chartRender }}