---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: "promote-${K8S_FUE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
spec:
  vars:
  - name: chartURL
    value: "${GH_CHART_URL}"

  - name: chartFolder
    value: ./chart-repo

  - name: chartRender
    value: ./chart-render

  - name: sourceImage
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/${K8S_FUE_NAME}"

  - name: sourceBranch
    value: main

  - name: stage
    value: ${{ ctx.stage }}

  - name: privateRepoFUE
    value: "${HARBOR_DNS}/${K8S_PROJECT_NAME}/${K8S_FUE_NAME}"

  - name: CHART_VALUES_PATH
    value: >-
      ${{
        // Compare ctx.stage with a dynamically constructed string
        ctx.stage == "dev-cluster-rs-01-${K8S_FUE_NAME}"       ? "thanh-fullend-chart/dev"      : 
        ctx.stage == "staging-cluster-rs-01-${K8S_FUE_NAME}"   ? "thanh-fullend-chart/staging"  : 
        ctx.stage == "prod-hcm-cluster-rs-02-${K8S_FUE_NAME}"  ? "thanh-fullend-chart/prod-hcm" : 
        ctx.stage == "prod-hni-cluster-rs-02-${K8S_FUE_NAME}"  ? "thanh-fullend-chart/prod-hni" : 
        "unknown-stage" 
      }}

  steps:
  - uses: git-clone
    as: git-clone-chart-repo
    config:
      repoURL: ${{ vars.chartURL }}
      checkout:
      - branch: ${{ vars.sourceBranch }}
        path: ${{ vars.chartFolder }}

      - branch: env/${{ vars.stage }}
        path: ${{ vars.chartRender }}
        create: true

  - uses: yaml-update
    as: update-chart-values-file
    config:
      path: ${{ vars.chartFolder }}/${{ vars.CHART_VALUES_PATH }}/values.yml
      updates:
      - key: fullend.image.repository
        value: ${{ vars.privateRepoFUE }}

      - key: fullend.image.tag
        value: ${{ imageFrom(vars.privateRepoFUE).Tag }}
        
      - key: fullend.image.pullPolicy
        value: Always

  - uses: git-commit
    as: commit-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      message: ${{ 'Update Helm values with ' + vars.privateRepoFUE + ' version ' + imageFrom(vars.privateRepoFUE).Tag }}

  - uses: git-push
    as: push-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      targetBranch: main

  - uses: argocd-update
    as: update-chart-repo
    config:
      apps:
      - name: "${{ ctx.stage }}"
        sources:
        - repoURL: "${GH_CHART_URL}"

  - uses: git-clear
    as: clear-branch-build-artifacts
    config:
      path: ${{ vars.chartRender }}

  - uses: helm-template
    as: helm-render-manifest
    config:
      path: ${{ vars.chartFolder }}/thanh-fullend-chart
      releaseName: thanh-fullend-chart
      useReleaseName: false
      valuesFiles:
      - ${{ vars.chartFolder }}/${{ vars.CHART_VALUES_PATH }}/values.yml
      outPath: ${{ vars.chartRender }}

  - uses: git-commit
    as: commit-manifest
    config:
      path: ${{ vars.chartRender }}
      message: ${{ 'Update ' + vars.CHART_VALUES_PATH + ' with ' + vars.privateRepoFUE + ' to version ' + imageFrom(vars.privateRepoFUE).Tag }}
  
  - uses: git-push
    as: push-manifest-branch
    config:
      path: ${{ vars.chartRender }}