---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: "dev-cluster-rs-01-${K8S_FUE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-${K8S_FUE_NAME}"
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: "promote-${K8S_FUE_NAME}"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: "staging-cluster-rs-01-${K8S_FUE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: rose
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-${K8S_FUE_NAME}"
    sources:
      stages:
      - "dev-cluster-rs-01-${K8S_FUE_NAME}"
  promotionTemplate:
    spec:
      steps:
      - task:
          name: "promote-${K8S_FUE_NAME}"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: "prod-hcm-cluster-rs-02-${K8S_FUE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: indigo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-${K8S_FUE_NAME}"
    sources:
      stages:
      - "staging-cluster-rs-01-${K8S_FUE_NAME}"
  promotionTemplate:
    spec:
      steps:
      - task:
          name: "promote-${K8S_FUE_NAME}"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: "prod-hni-cluster-rs-02-${K8S_FUE_NAME}"
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: gray
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-${K8S_FUE_NAME}"
    sources:
      stages:
      - "staging-cluster-rs-01-${K8S_FUE_NAME}"
  promotionTemplate:
    spec:
      steps:
      - task:
          name: "promote-${K8S_FUE_NAME}"
