---
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
data:
  vault-root-token: "${VAULT_ROOT_TOKEN_BASE_64}"

---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: hashicorp-vault-k8s-cluster-mgmt
spec:
  provider:
    vault:
      server: "${VAULT_ADDR}"
      path: "${VAULT_KV}"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          key: "vault-root-token"
