---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "hashicorp-vault-${VAULT_KV}-${VAULT_KV_PATH}"
spec:
  provider:
    vault:
      server: "${VAULT_ADDR}"
      path: "${VAULT_KV}"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          key: "vault-root-token"
          namespace: hashicorp-vault

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${VAULT_KV}-${VAULT_KV_PATH}"
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: "hashicorp-vault-${VAULT_KV}-${VAULT_KV_PATH}"
    kind: ClusterSecretStore
  data:
  - secretKey: GH_TOKEN
    remoteRef:
      key: "${VAULT_KV}/${VAULT_KV_PATH}"
      property: GH_TOKEN

  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      key: "${VAULT_KV}/${VAULT_KV_PATH}"
      property: HARBOR_ADMIN_PASSWORD

  - secretKey: TELEGRAM_BOT_TOKEN
    remoteRef:
      key: "${VAULT_KV}/${VAULT_KV_PATH}"
      property: TELEGRAM_BOT_TOKEN

  # https://hub.tekton.dev/tekton/task/kaniko
  # default value `config.json`
  - secretKey: config.json
    remoteRef:
      key: "${VAULT_KV}/${VAULT_KV_PATH}"
      property: HARBOR_CONFIG_JSON
