---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: "${K8S_PROJECT_NAME}-application-set"
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          # DEV environment
          - name: dev
            cluster: cluster-rs-01
            appType: "${K8S_BE_NAME}"
            server: "${K8S_CLUSTER_RS_01}"

          - name: dev
            cluster: cluster-rs-01
            appType: "${K8S_FE_NAME}"
            server: "${K8S_CLUSTER_RS_01}"

          - name: dev
            cluster: cluster-rs-01
            appType: "${K8S_FUE_NAME}"
            server: "${K8S_CLUSTER_RS_01}"

          # STAGING environment
          - name: staging
            cluster: cluster-rs-01
            appType: "${K8S_BE_NAME}"
            server: "${K8S_CLUSTER_RS_01}"

          - name: staging
            cluster: cluster-rs-01
            appType: "${K8S_FE_NAME}"
            server: "${K8S_CLUSTER_RS_01}"

          - name: staging
            cluster: cluster-rs-01
            appType: "${K8S_FUE_NAME}"
            server: "${K8S_CLUSTER_RS_01}"

          # PROD HCM environments
          - name: prod-hcm
            cluster: cluster-rs-02
            appType: "${K8S_BE_NAME}"
            server: "${K8S_CLUSTER_RS_02}"

          - name: prod-hcm
            cluster: cluster-rs-02
            appType: "${K8S_FE_NAME}"
            server: "${K8S_CLUSTER_RS_02}"

          - name: prod-hcm
            cluster: cluster-rs-02
            appType: "${K8S_FUE_NAME}"
            server: "${K8S_CLUSTER_RS_02}"

          # PROD HNI environments
          - name: prod-hni
            cluster: cluster-rs-02
            appType: "${K8S_BE_NAME}"
            server: "${K8S_CLUSTER_RS_02}"

          - name: prod-hni
            cluster: cluster-rs-02
            appType: "${K8S_FE_NAME}"
            server: "${K8S_CLUSTER_RS_02}"
 
          - name: prod-hni
            cluster: cluster-rs-02
            appType: "${K8S_FUE_NAME}"
            server: "${K8S_CLUSTER_RS_02}"

  template:
    metadata:
      name: "{{.name}}-{{.cluster}}-{{.appType}}"
      annotations:
        kargo.akuity.io/authorized-stage: "${K8S_PROJECT_NAME}:{{.name}}-{{.cluster}}-{{.appType}}"
    spec:
      project: "${K8S_PROJECT_NAME}"
      sources:
      - repoURL: "${GH_CHART_URL}"
        targetRevision: main
        path: >
          {{- if eq .appType "frontend-application" -}}
          thanh-backend-chart
          {{- else if eq .appType "backend-application" -}}
          thanh-frontend-chart
          {{- else if eq .appType "fullend-application" -}}
          thanh-fullend-chart
          {{- end -}}
        helm:
          valueFiles:
            - "{{.name}}/values.yml"
      destination:
        server: "{{.server}}"
        namespace: "${K8S_PROJECT_NAME}-{{.name}}-{{.appType}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
