---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-cluster-mgmt
spec:
  refreshInterval: "600s"
  secretStoreRef:
    name: hashicorp-vault-k8s-cluster-mgmt
    kind: ClusterSecretStore
  data:
  - secretKey: GH_TOKEN
    remoteRef:
      key: "${VAULT_KV}/${VAULT_KV_PATH}"
      property: GH_TOKEN

  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      key: "${VAULT_KV}/${VAULT_KV_PATH}"
      property: HARBOR_ADMIN_PASSWORD
