---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-trigger-binding-${K8S_BE_NAME}
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: application
      value: ${K8S_BE_NAME}

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-trigger-binding-${K8S_FE_NAME}
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: application
    value: ${K8S_FE_NAME}

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-trigger-binding-${K8S_FUE_NAME}
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: application
    value: ${K8S_FUE_NAME}

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
 name: multi-app-event-listener
spec:
  serviceAccountName: tekton-service-account
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  triggers:
    - name: github-listener-${K8S_BE_NAME}
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("backend-application/")'
      bindings:
        - ref: "github-trigger-binding-${K8S_BE_NAME}"
      template:
        ref: multi-app-pipeline

    - name: github-listener-${K8S_FE_NAME}
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("frontend-application/")'
      bindings:
        - ref: github-trigger-binding-${K8S_FE_NAME}
      template:
        ref: multi-app-pipeline

    - name: github-listener-${K8S_FUE_NAME}
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("fullend-application/")'
      bindings:
        - ref: github-trigger-binding-${K8S_FUE_NAME}
      template:
        ref: multi-app-pipeline
